import { useEffect, useMemo, useState } from "react";
import { ChevronDown, ChevronLeft, ChevronRight, Mail } from "lucide-react";
import { Sheet, SheetContent } from "@/components/ui/sheet";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { cn } from "@/lib/utils";
import { menusPorAmbiente, nomesAmbiente, type Ambiente, type ItemMenu } from "@/types/navegacao";
import { LogoShare } from "@/components/layout/TopBar";

const gruposFixos = ["Navegação principal", "Rotinas do departamento"];

export function Sidebar({ ambiente, menuAtivo, aberta, recolhida, aoFechar, aoAlternarRecolhimento, aoSelecionar }: { ambiente: Ambiente; menuAtivo: string; aberta: boolean; recolhida: boolean; aoFechar: () => void; aoAlternarRecolhimento: () => void; aoSelecionar: (menu: string) => void }) {
  const [gruposAbertos, setGruposAbertos] = useState(gruposFixos);
  const [naoLidas] = useState(0);
  const itens = useMemo(() => menusPorAmbiente[ambiente], [ambiente]);
  const grupos = useMemo(() => [{ title: gruposFixos[0], items: itens.slice(0, 1) }, { title: gruposFixos[1], items: itens.slice(1) }], [itens]);
  useEffect(() => { setGruposAbertos(gruposFixos); }, [ambiente]);
  const selecionar = (id: string) => { aoSelecionar(id); aoFechar(); };
  const renderItem = (item: ItemMenu, compacto = false) => { const Icon = item.icon; const selecionado = menuAtivo === item.id; return <button type="button" key={item.id} onClick={() => selecionar(item.id)} title={compacto ? item.label : undefined} className={cn(compacto ? "group relative flex h-10 w-10 items-center justify-center rounded-full border" : "flex w-full items-center gap-3 rounded-lg border px-3 py-2.5 text-left", "text-[11px] font-semibold transition-all", selecionado ? "border-sidebar-primary bg-sidebar-primary/15 text-sidebar-primary" : "border-transparent text-sidebar-foreground/70 hover:border-sidebar-border hover:bg-sidebar-accent hover:text-sidebar-foreground")}><Icon size={compacto ? 18 : 16} strokeWidth={selecionado ? 2.3 : 1.8} />{!compacto && <span className="min-w-0 flex-1 truncate">{item.label}</span>}{!compacto && item.badge && <span className="rounded-full bg-primary px-1.5 py-0.5 text-[9px] font-bold text-primary-foreground">{item.badge}</span>}{compacto && <span className="pointer-events-none absolute left-full ml-3 whitespace-nowrap rounded-md border border-sidebar-border bg-sidebar px-2.5 py-1 text-xs text-sidebar-foreground opacity-0 shadow-lg transition-opacity group-hover:opacity-100">{item.label}</span>}</button>; };
  return <><div className="fixed left-0 top-[68px] z-30 hidden h-[calc(100dvh-68px)] w-[76px] flex-col items-center border-r border-sidebar-border bg-sidebar py-4 md:flex">{recolhida ? <button type="button" aria-label="Expandir menu" onClick={aoAlternarRecolhimento} className="flex h-10 w-10 items-center justify-center rounded-full border border-sidebar-border bg-sidebar text-sidebar-foreground shadow-lg hover:bg-sidebar-accent"><ChevronRight size={18} /></button> : <><button type="button" aria-label="Recolher menu" onClick={aoAlternarRecolhimento} className="mb-4 flex h-9 w-9 items-center justify-center rounded-full border border-sidebar-border bg-sidebar-accent/60 text-sidebar-foreground hover:bg-sidebar-accent"><ChevronLeft size={16} /></button><nav className="flex w-full flex-col items-center gap-3 px-2">{itens.map((item) => renderItem(item, true))}</nav></>}</div><Sheet open={aberta} onOpenChange={(open) => !open && aoFechar()}><SheetContent side="left" className="w-80 border-sidebar-border bg-sidebar p-0 text-sidebar-foreground"><div className="flex h-[68px] items-center border-b border-sidebar-border px-6"><LogoShare /><span className="ml-auto rounded-md border border-sidebar-border px-2 py-1 font-mono text-[9px] text-sidebar-foreground/40">{nomesAmbiente[ambiente]}</span></div><nav className="h-[calc(100dvh-68px)] space-y-3 overflow-y-auto p-4">{grupos.map((grupo) => <Collapsible key={grupo.title} open={gruposAbertos.includes(grupo.title)} onOpenChange={() => setGruposAbertos((atual) => atual.includes(grupo.title) ? atual.filter((item) => item !== grupo.title) : [...atual, grupo.title])} className="rounded-xl border border-sidebar-border bg-sidebar-accent/25"><CollapsibleTrigger className="flex w-full items-center justify-between px-3.5 py-3 text-left text-[10px] font-bold uppercase tracking-[.12em] text-sidebar-foreground/60"><span>{grupo.title}</span>{gruposAbertos.includes(grupo.title) ? <ChevronDown size={15} /> : <ChevronRight size={15} />}</CollapsibleTrigger><CollapsibleContent className="space-y-1 px-2 pb-2">{grupo.items.map((item) => renderItem(item))}</CollapsibleContent></Collapsible>)}</nav></SheetContent></Sheet><span className="sr-only"><Mail aria-hidden="true" />{naoLidas}</span></>;
}
