import { useState } from "react";
import { CheckSquare, Fuel, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { salvarChecklistPreVoo, type SolicitacaoVooInterna } from "@/lib/colaborador-api";

export default function ChecklistPreVoo({ item }: { item: SolicitacaoVooInterna }) {
  const [aberto, setAberto] = useState(false); const [itens, setItens] = useState<Record<string, boolean>>({ documentos: false, meteorologia: false, aeronave: false, peso_balanceamento: false, comunicacao: false }); const [litros, setLitros] = useState(""); const [comanda, setComanda] = useState(""); const [local, setLocal] = useState(item.origem); const [obs, setObs] = useState(""); const [salvando, setSalvando] = useState(false); const [ok, setOk] = useState(false);
  const salvar = async () => { setSalvando(true); try { await salvarChecklistPreVoo(item.id, { itens, observacoes: obs, abastecimento: Number(litros) > 0 ? { litros: Number(litros), local, numero_comanda: comanda } : undefined, status: "concluido" }); setOk(true); } finally { setSalvando(false); } };
  return <section className="rounded-xl border border-primary/25 bg-card/75 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><CheckSquare size={16} className="text-primary" /><div><h2 className="text-xs font-bold">Checklist pré-voo</h2><p className="text-[10px] text-muted-foreground">Confirme os itens antes da operação de {item.numero_voo || "voo aprovado"}.</p></div></div><Button variant={aberto ? "default" : "outline"} className="h-8 text-[10px]" onClick={() => setAberto(!aberto)}>{aberto ? "Fechar checklist" : "Abrir checklist"}</Button></div>{aberto && <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="space-y-2">{Object.entries(itens).map(([chave, marcado]) => <label key={chave} className="flex items-center gap-2 rounded-lg border border-border bg-secondary/20 p-2 text-[11px]"><input type="checkbox" checked={marcado} onChange={(e) => setItens({ ...itens, [chave]: e.target.checked })} className="h-4 w-4 accent-primary" /> {chave.replaceAll("_", " ")}</label>)}<textarea value={obs} onChange={(e) => setObs(e.target.value)} placeholder="Observações do checklist" className="min-h-20 w-full rounded-lg border border-border bg-background p-2 text-xs" /></div><div className="rounded-lg border border-border bg-secondary/20 p-3"><p className="flex items-center gap-2 text-[10px] font-bold uppercase text-primary"><Fuel size={13} /> Abastecimento no checklist</p><p className="mt-1 text-[10px] text-muted-foreground">A comanda fica pendente para o financeiro completar nota fiscal e boleto.</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><input type="number" min="0" step="0.01" value={litros} onChange={(e) => setLitros(e.target.value)} placeholder="Litros" className="h-9 rounded-lg border border-border bg-background px-3 text-xs" /><input value={local} onChange={(e) => setLocal(e.target.value)} placeholder="Local" className="h-9 rounded-lg border border-border bg-background px-3 text-xs" /><input value={comanda} onChange={(e) => setComanda(e.target.value)} placeholder="Número da comanda" className="h-9 rounded-lg border border-border bg-background px-3 text-xs sm:col-span-2" /></div><Button onClick={() => void salvar()} disabled={salvando} className="mt-3 h-9 gap-2 text-[10px]"><Save size={13} />{salvando ? "Salvando..." : "Salvar checklist"}</Button>{ok && <p className="mt-2 text-[10px] text-emerald-300">Checklist salvo e abastecimento enviado para o financeiro.</p>}</div></div>}</section>;
}
