import { useState } from "react";
import { ChevronDown, Landmark, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { salvarContaBancariaEmail, type ContaBancariaEmail } from "@/lib/colaborador-api";

interface Props { contas: ContaBancariaEmail[]; onSaved: () => void; }
const campos: Array<[keyof Omit<ContaBancariaEmail, "id" | "texto">, string]> = [["banco", "Banco"], ["agencia", "Agência"], ["numero_conta", "Conta"], ["tipo_conta", "Tipo de conta"], ["cnpj", "CNPJ"], ["razao_social", "Razão social"], ["pix", "PIX"]];
export default function ConfiguracaoContasBancarias({ contas, onSaved }: Props) {
  const [aberta, setAberta] = useState<string | null>(null);
  const [rascunhos, setRascunhos] = useState<Record<string, Partial<ContaBancariaEmail>>>({});
  const [salvando, setSalvando] = useState<string | null>(null);
  const [mensagem, setMensagem] = useState("");
  const obter = (conta: ContaBancariaEmail) => ({ ...conta, ...(rascunhos[conta.id] || {}) });
  const alterar = (conta: ContaBancariaEmail, campo: keyof ContaBancariaEmail, valor: string) => setRascunhos((atual) => ({ ...atual, [conta.id]: { ...atual[conta.id], [campo]: valor } }));
  const salvar = async (conta: ContaBancariaEmail) => { const dados = obter(conta); setSalvando(conta.id); setMensagem(""); try { await salvarContaBancariaEmail(conta.id, { banco: dados.banco, agencia: dados.agencia, numero_conta: dados.numero_conta, tipo_conta: dados.tipo_conta, cnpj: dados.cnpj, razao_social: dados.razao_social, pix: dados.pix }); setMensagem("Dados bancários salvos."); setRascunhos((atual) => { const next = { ...atual }; delete next[conta.id]; return next; }); onSaved(); } catch (e) { setMensagem(e instanceof Error ? e.message : "Não foi possível salvar os dados bancários."); } finally { setSalvando(null); } };
  return <div className="space-y-3"><div><h2 className="text-sm font-bold">Dados bancários</h2><p className="mt-1 text-[10px] text-muted-foreground">Recolha ou expanda uma conta. Edite e salve os dados diretamente em contas_bancarias.</p></div>{mensagem && <p className="rounded-lg border border-emerald-500/20 bg-emerald-500/10 p-3 text-xs text-emerald-600">{mensagem}</p>}{contas.length === 0 ? <p className="rounded-xl border border-dashed border-border p-5 text-center text-xs text-muted-foreground">Nenhuma conta bancária cadastrada.</p> : contas.map((conta) => { const dados = obter(conta); const expandida = aberta === conta.id; return <div key={conta.id} className="overflow-hidden rounded-xl border border-border/60 bg-muted/20"><button type="button" onClick={() => setAberta(expandida ? null : conta.id)} className="flex w-full items-center justify-between gap-3 p-4 text-left hover:bg-muted/40"><span className="flex items-center gap-2"><Landmark size={17} className="text-primary" /><span><strong className="block text-xs">{dados.banco || "Conta bancária"}</strong><span className="mt-1 block text-[10px] text-muted-foreground">{dados.tipo_conta || "Conta"} {dados.numero_conta || ""}</span></span></span><ChevronDown size={16} className={`transition-transform ${expandida ? "rotate-180" : ""}`} /></button>{expandida && <div className="grid gap-3 border-t border-border/60 p-4 sm:grid-cols-2">{campos.map(([campo, label]) => <label key={campo} className="block"><span className="mb-1 block text-[10px] font-semibold text-muted-foreground">{label}</span><Input value={String(dados[campo] || "")} onChange={(e) => alterar(conta, campo, e.target.value)} className="h-9 rounded-lg text-xs" /></label>)}<div className="flex justify-end sm:col-span-2"><Button type="button" onClick={() => void salvar(conta)} disabled={salvando === conta.id} className="h-9 gap-2 text-xs"><Save size={14} />{salvando === conta.id ? "Salvando..." : "Salvar conta"}</Button></div></div>}</div>; })}</div>;
}
