import { useEffect, useState } from "react";
import { API_BASE } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

function moeda(v: unknown) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(v) || 0); }
function dataBr(v: unknown) { const [a,m,d] = String(v || "").slice(0, 10).split("-"); return a && m && d ? `${d}/${m}/${a}` : "—"; }
export default function AprovacaoRelatorioViagem() {
  const token = new URLSearchParams(window.location.search).get("token") || window.location.pathname.split("/").pop() || "";
  const [data, setData] = useState<any>(null); const [motivo, setMotivo] = useState(""); const [mensagem, setMensagem] = useState("Carregando relatório..."); const [enviando, setEnviando] = useState(false);
  useEffect(() => { void fetch(`${API_BASE}/api/public/relatorios-despesa-viagem/aprovacao/${encodeURIComponent(token)}`).then(async r => { const json = await r.json(); if (!r.ok) throw new Error(json.error); setData(json); setMensagem(""); }).catch(e => setMensagem(e.message || "Link inválido ou expirado.")); }, [token]);
  const decidir = async (aprovado: boolean) => { if (!aprovado && !motivo.trim()) { setMensagem("Informe o motivo da rejeição."); return; } setEnviando(true); try { const r = await fetch(`${API_BASE}/api/public/relatorios-despesa-viagem/aprovacao/${encodeURIComponent(token)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ aprovado, motivo }) }); const json = await r.json(); if (!r.ok) throw new Error(json.error); setData((atual: any) => ({ ...atual, relatorio: json.relatorio })); setMensagem(aprovado ? "Sua despesa foi aprovada." : "Sua rejeição foi registrada."); } catch (e) { setMensagem(e instanceof Error ? e.message : "Não foi possível registrar a decisão."); } finally { setEnviando(false); } };
  if (!data) return <main className="min-h-screen bg-[#030814] p-6 text-white"><div className="mx-auto max-w-xl rounded-xl border border-white/10 bg-white/5 p-6">{mensagem}</div></main>;
  const r = data.relatorio; const despesas = (r.despesas || []).filter((d: any) => String(d.pago_por || "").includes(`tripulante_${data.tripulante_pos}`));
  return <main className="min-h-screen bg-[#030814] p-4 text-white sm:p-8"><div className="mx-auto max-w-3xl space-y-5"><header><p className="text-xs uppercase tracking-[0.2em] text-cyan-300">Share Brasil · Aprovação de despesas</p><h1 className="mt-2 text-2xl font-bold">Relatório {r.numero_relatorio}</h1><p className="text-sm text-white/60">Voo {r.numero_voo || "—"} · Aeronave {r.aeronave_matricula || "—"} · {dataBr(r.data_inicio)} a {dataBr(r.data_fim)}</p></header><section className="rounded-xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold">Dados da viagem</h2><p className="mt-2 text-sm text-white/70">Rota: {r.rota || "—"}</p><p className="text-sm text-white/70">Tripulante {data.tripulante_pos}: {data.tripulante_pos === 1 ? r.nome_tripulante : r.nome_tripulante_2}</p></section><section className="overflow-hidden rounded-xl border border-white/10 bg-white/5"><div className="border-b border-white/10 p-5"><h2 className="font-semibold">Suas despesas</h2></div><div className="divide-y divide-white/10">{despesas.map((d: any, i: number) => <div className="flex items-start justify-between gap-4 p-5" key={i}><div><p className="font-medium">{d.descricao || d.categoria || "Despesa"}</p><p className="text-xs text-white/50">{dataBr(d.data)} · {d.categoria || "Outros"}</p></div><strong>{moeda(d.valor)}</strong></div>)}{!despesas.length && <p className="p-5 text-sm text-white/60">Nenhuma despesa atribuída a você.</p>}</div></section><Textarea value={motivo} onChange={e => setMotivo(e.target.value)} placeholder="Motivo (obrigatório se rejeitar)" className="min-h-24 bg-white/5 text-white" /><div className="flex flex-wrap gap-3"><Button disabled={enviando} onClick={() => void decidir(true)} className="bg-emerald-600 hover:bg-emerald-500">Aprovar minhas despesas</Button><Button disabled={enviando} variant="outline" onClick={() => void decidir(false)} className="border-rose-400/50 text-rose-200">Rejeitar e informar motivo</Button></div>{mensagem && <p className="text-sm text-cyan-200">{mensagem}</p>}</div></main>;
}
