import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CalendarDays, Check, CheckCircle2, Clock3, RefreshCw, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CabecalhoSecao, CartaoKpi, EstadoVazio, EtiquetaStatus, IndicadorPagina } from "@/components/dashboard/PrimitivosDashboard";
import { atualizarFeriasGestor, buscarFeriasCorporativas, type FeriasCorporativasResponse } from "@/lib/colaborador-api";

const dataHoje = () => new Date().toISOString().slice(0, 10);
const dataBr = (value?: string | null) => value ? new Date(`${value.slice(0, 10)}T00:00:00`).toLocaleDateString("pt-BR") : "—";
const status = (value: string) => value === "aprovada" ? { label: "Aprovada", tone: "green" as const } : value === "solicitada" ? { label: "Solicitada", tone: "amber" as const } : value === "reprovada" ? { label: "Reprovada", tone: "red" as const } : { label: value, tone: "neutral" as const };

type Registro = FeriasCorporativasResponse["registros"][number];

export default function Ferias() {
  const [dados, setDados] = useState<FeriasCorporativasResponse | null>(null);
  const [referencia, setReferencia] = useState(dataHoje);
  const [carregando, setCarregando] = useState(true);
  const [atualizandoId, setAtualizandoId] = useState<string | null>(null);
  const [erro, setErro] = useState("");
  const [aviso, setAviso] = useState("");
  const carregar = useCallback(async () => { setCarregando(true); setErro(""); try { setDados(await buscarFeriasCorporativas(referencia)); } catch (cause) { setErro(cause instanceof Error ? cause.message : "Não foi possível carregar o quadro corporativo."); } finally { setCarregando(false); } }, [referencia]);
  useEffect(() => { void carregar(); }, [carregar]);
  const registros = useMemo(() => dados?.registros || [], [dados]);
  const ativas = registros.filter((item) => item.status === "aprovada" && item.data_inicio <= referencia && item.data_fim >= referencia);
  const solicitadas = registros.filter((item) => item.status === "solicitada");
  const vencidas = registros.filter((item) => item.status === "aprovada" && item.data_fim < referencia);
  const atualizarStatus = async (item: Registro, next: "aprovada" | "reprovada") => {
    const motivo = next === "reprovada" ? window.prompt("Informe o motivo da reprovação:")?.trim() : undefined;
    if (next === "reprovada" && !motivo) return;
    setAtualizandoId(item.id); setErro(""); setAviso("");
    try { await atualizarFeriasGestor(item.id, { status: next, ...(motivo ? { motivo_reprovacao: motivo } : {}) }); setAviso(next === "aprovada" ? "Solicitação aprovada." : "Solicitação reprovada."); await carregar(); } catch (cause) { setErro(cause instanceof Error ? cause.message : "Não foi possível atualizar a solicitação."); } finally { setAtualizandoId(null); }
  };
  return <div className="route-enter space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><IndicadorPagina>Gestor / RH / calendário</IndicadorPagina><h1 className="mt-1 flex items-center gap-2 text-2xl font-extrabold tracking-[-.04em] md:text-[30px]"><CalendarDays className="text-primary" size={26} /> Férias</h1><p className="mt-1.5 text-xs text-muted-foreground">Quadro geral da empresa, análise de solicitações e calendário de períodos.</p></div><div className="flex items-center gap-2"><input aria-label="Data de referência" type="date" value={referencia} onChange={(event) => setReferencia(event.target.value)} className="h-9 rounded-lg border border-border bg-card px-3 text-xs" /><Button type="button" variant="outline" onClick={() => void carregar()} disabled={carregando} className="h-9 gap-1.5 text-[10px]"><RefreshCw size={13} className={carregando ? "animate-spin" : ""} /> Atualizar</Button></div></div>
    {(erro || aviso) && <div className={`rounded-lg border p-3 text-[11px] ${erro ? "border-red-400/30 bg-red-400/10 text-red-200" : "border-emerald-400/30 bg-emerald-400/10 text-emerald-200"}`}>{erro || aviso}</div>}
    <div className="grid gap-3 sm:grid-cols-3"><CartaoKpi label="Em férias hoje" value={carregando ? "—" : String(dados?.resumo.ativas ?? ativas.length)} detail={`Referência ${dataBr(referencia)}`} tone="green" icon={<CheckCircle2 size={16} />} /><CartaoKpi label="Solicitações pendentes" value={carregando ? "—" : String(dados?.resumo.solicitadas ?? solicitadas.length)} detail="Aguardando análise do RH" tone="amber" icon={<Clock3 size={16} />} /><CartaoKpi label="Períodos vencidos" value={carregando ? "—" : String(dados?.resumo.vencidas ?? vencidas.length)} detail="Exigem regularização" tone="red" icon={<AlertTriangle size={16} />} /></div>
    {carregando ? <div className="skeleton h-80 rounded-xl" /> : <div className="grid gap-5 xl:grid-cols-3"><Painel titulo="Em férias na data" icon={<CheckCircle2 size={15} />} items={ativas} vazio="Nenhum colaborador em férias na data escolhida" /><Painel titulo="Solicitações" icon={<Clock3 size={15} />} items={solicitadas} vazio="Nenhuma solicitação pendente" onApprove={atualizarStatus} /><Painel titulo="Vencidas" icon={<AlertTriangle size={15} />} items={vencidas} vazio="Nenhum período vencido" /></div>}
    <section className="overflow-hidden rounded-xl border border-border bg-card/75"><CabecalhoSecao icon={<Users size={15} />} title="Agenda corporativa" detail={`${registros.length} registros encontrados no D1`} />{!carregando && registros.length === 0 ? <EstadoVazio label="Nenhum registro de férias encontrado" /> : <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead><tr className="border-b border-border text-[9px] font-bold uppercase tracking-[.11em] text-muted-foreground"><th className="px-4 py-3">Colaborador</th><th className="px-4 py-3">Departamento</th><th className="px-4 py-3">Período</th><th className="px-4 py-3">Dias</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Ações</th></tr></thead><tbody>{registros.map((item) => { const tone = status(item.status); return <tr key={item.id} className="border-b border-border/60 last:border-0 hover:bg-secondary/20"><td className="px-4 py-3"><p className="text-[10px] font-bold">{item.nome_exibicao || item.nome_completo || item.email || item.colaborador_id}</p><p className="mt-1 text-[9px] text-muted-foreground">{item.email || "—"}</p></td><td className="px-4 py-3 text-[10px] text-muted-foreground">{item.departamento || "—"}</td><td className="px-4 py-3 text-[10px]">{dataBr(item.data_inicio)} a {dataBr(item.data_fim)}</td><td className="px-4 py-3 font-mono text-[10px]">{item.quantidade_dias}</td><td className="px-4 py-3"><EtiquetaStatus tone={tone.tone}>{tone.label}</EtiquetaStatus></td><td className="px-4 py-3">{item.status === "solicitada" ? <div className="flex gap-1.5"><Button type="button" disabled={atualizandoId === item.id} onClick={() => void atualizarStatus(item, "aprovada")} className="h-7 gap-1 px-2 text-[9px]"><Check size={11} /> Aprovar</Button><Button type="button" variant="outline" disabled={atualizandoId === item.id} onClick={() => void atualizarStatus(item, "reprovada")} className="h-7 gap-1 border-red-400/30 px-2 text-[9px] text-red-300"><X size={11} /> Reprovar</Button></div> : <span className="text-[10px] text-muted-foreground">{item.aprovado_em ? `Analisada em ${dataBr(item.aprovado_em)}` : "—"}</span>}</td></tr>; })}</tbody></table></div>}</section>
  </div>;
}
function Painel({ titulo, icon, items, vazio, onApprove }: { titulo: string; icon: React.ReactNode; items: Registro[]; vazio: string; onApprove?: (item: Registro, next: "aprovada" | "reprovada") => Promise<void> }) { return <section className="overflow-hidden rounded-xl border border-border bg-card/75"><CabecalhoSecao icon={icon} title={titulo} detail={`${items.length} registro(s)`} />{items.length === 0 ? <EstadoVazio label={vazio} /> : <div className="divide-y divide-border/60">{items.slice(0, 8).map((item) => <div key={item.id} className="p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold">{item.nome_exibicao || item.nome_completo || item.email}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.departamento || "Departamento não informado"}</p></div><span className="font-mono text-[10px] text-primary">{item.quantidade_dias}d</span></div><p className="mt-3 text-[10px] text-muted-foreground">{dataBr(item.data_inicio)} a {dataBr(item.data_fim)}</p>{onApprove && <div className="mt-3 flex gap-2"><Button type="button" onClick={() => void onApprove(item, "aprovada")} className="h-7 gap-1 px-2 text-[9px]"><Check size={11} /> Aprovar</Button><Button type="button" variant="outline" onClick={() => void onApprove(item, "reprovada")} className="h-7 gap-1 border-red-400/30 px-2 text-[9px] text-red-300"><X size={11} /> Reprovar</Button></div>}</div>)}</div>}</section>; }
