import { useEffect, useState } from "react";
import { CreditCard, FileCheck2, LogOut, Menu, Plane, UserRound } from "lucide-react";
import { Navigate, useNavigate } from "react-router-dom";
import { clearAuthSession, getCurrentSession, type AuthUser } from "@/lib/api";
import { CartaoKpi, CabecalhoSecao, EtiquetaStatus, EstadoVazio } from "@/components/dashboard/PrimitivosDashboard";

export default function PortalClienteApp() {
  const navigate = useNavigate();
  const [usuario, setUsuario] = useState<AuthUser | null>(null);
  const [verificando, setVerificando] = useState(true);
  useEffect(() => { void getCurrentSession().then((sessao) => { setUsuario(sessao); setVerificando(false); }); }, []);
  const sair = () => { clearAuthSession(); navigate("/portal-cliente/login", { replace: true }); };
  if (verificando) return <div className="min-h-screen bg-background" aria-label="Verificando sessão do cliente" />;
  if (!usuario) return <Navigate to="/portal-cliente/login" replace />;
  return <div className="min-h-screen bg-background"><header className="sticky top-0 z-20 flex min-h-[70px] items-center justify-between border-b border-border/70 bg-background/90 px-5 backdrop-blur-xl md:px-10"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><Plane size={18} /></div><div><p className="text-sm font-extrabold tracking-[.16em]">SHARE BRASIL</p><p className="text-[10px] text-muted-foreground">Portal do Cliente</p></div></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-[10px] text-muted-foreground sm:flex"><UserRound size={13} className="text-primary" />{usuario.nome_exibicao || usuario.login}</div><button type="button" onClick={sair} className="flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-[10px] font-bold text-muted-foreground hover:bg-secondary hover:text-foreground"><LogOut size={14} /> Sair</button><Menu className="text-muted-foreground sm:hidden" size={18} /></div></header><main className="mx-auto w-full max-w-[1220px] px-5 py-7 md:px-10 md:py-10"><div className="mb-7"><p className="mb-2 text-[10px] font-bold uppercase tracking-[.2em] text-primary">Área do cliente</p><h1 className="text-3xl font-extrabold tracking-[-.05em]">Olá, {usuario.nome_exibicao || usuario.login}</h1><p className="mt-2 text-sm text-muted-foreground">Consulte seus pagamentos e documentos em um ambiente separado do sistema interno.</p></div><div className="mb-6 grid gap-3 sm:grid-cols-3"><CartaoKpi label="Em aberto" value="R$ 4.475" detail="2 cobranças aguardando pagamento" tone="amber" icon={<CreditCard size={16} />} /><CartaoKpi label="Pagos no mês" value="R$ 18.260" detail="5 lançamentos confirmados" tone="green" icon={<FileCheck2 size={16} />} /><CartaoKpi label="Documentos" value="08" detail="Disponíveis para consulta" tone="violet" icon={<FileCheck2 size={16} />} /></div><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><section className="overflow-hidden rounded-xl border border-border bg-card/75"><CabecalhoSecao icon={<CreditCard size={15} />} title="Pagamentos recentes" detail="Acompanhe os lançamentos enviados para você" /><div className="divide-y divide-border/70"><Pagamento descricao="Combustível · JET" detalhe="Vencimento 02 set. 2026" valor="R$ 4.475" status="Pendente" tone="amber" /><Pagamento descricao="Administração Share · agosto" detalhe="Pago em 05 ago. 2026" valor="R$ 18.260" status="Pago" tone="green" /><Pagamento descricao="Tarifa aeroportuária" detalhe="Pago em 29 jul. 2026" valor="R$ 392" status="Pago" tone="green" /></div></section><section className="overflow-hidden rounded-xl border border-border bg-card/75"><CabecalhoSecao icon={<FileCheck2 size={15} />} title="Documentos disponíveis" detail="Últimos arquivos enviados" /><EstadoVazio label="Documentos carregados pela administração" /></section></div></main></div>;
}
function Pagamento({ descricao, detalhe, valor, status, tone }: { descricao: string; detalhe: string; valor: string; status: string; tone: "amber" | "green" }) { return <div className="flex items-center gap-3 p-4"><div className={`flex h-8 w-8 items-center justify-center rounded-lg ${tone === "green" ? "bg-[#5bbd75]/10 text-[#6bd188]" : "bg-[#f1c348]/10 text-[#f4cc64]"}`}><CreditCard size={14} /></div><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-bold">{descricao}</p><p className="mt-1 text-[9px] text-muted-foreground">{detalhe}</p></div><div className="text-right"><p className="font-mono text-[11px] font-bold">{valor}</p><EtiquetaStatus tone={tone}>{status}</EtiquetaStatus></div></div>; }
