import { useEffect, useMemo, useState } from "react";
import { BookOpen, ExternalLink, FileText, GraduationCap, Plus, Trash2, Upload, Video } from "lucide-react";
import { Button } from "@/components/ui/button";
import { buscarMateriaisCentro, buscarPerfilColaborador, carregarMaterialCentro, criarMaterialCentro, excluirMaterialCentro, type MaterialTreinamento } from "@/lib/colaborador-api";
import { IndicadorPagina } from "@/components/dashboard/PrimitivosDashboard";

const card = "rounded-xl border border-border bg-card/80 shadow-sm";
function managerRole(value?: string | null) { return ["admin", "administrador", "gestor_master", "gestormaster"].includes((value || "").toLowerCase().replace(/[\s-]+/g, "_")); }

export default function CentroMateriais({ categoria }: { categoria: "TUTORIAL" | "TREINAMENTO" }) {
  const [items, setItems] = useState<MaterialTreinamento[]>([]);
  const [isManager, setIsManager] = useState(false);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [formOpen, setFormOpen] = useState(false);
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [theme, setTheme] = useState("");
  const [videoUrl, setVideoUrl] = useState("");
  const [html, setHtml] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const heading = categoria === "TUTORIAL" ? "Tutorial" : "Treinamento";
  const Icon = categoria === "TUTORIAL" ? BookOpen : GraduationCap;

  const load = async () => { setLoading(true); setError(""); try { const [materials, profile] = await Promise.all([buscarMateriaisCentro(categoria), buscarPerfilColaborador()]); setItems(materials); setIsManager(managerRole(profile.perfil.tipo_user)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar os materiais."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [categoria]);
  const grouped = useMemo(() => items.reduce<Record<string, MaterialTreinamento[]>>((acc, item) => { const key = item.tema || "Materiais gerais"; (acc[key] ||= []).push(item); return acc; }, {}), [items]);
  const reset = () => { setTitle(""); setDescription(""); setTheme(""); setVideoUrl(""); setHtml(""); setFile(null); setFormOpen(false); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!title.trim()) return; setBusy(true); setError(""); const body = new FormData(); body.append("titulo", title); body.append("descricao", description); body.append("tema", theme); body.append("video_url", videoUrl); body.append("conteudo_html", html); if (file) body.append("arquivo", file); try { await criarMaterialCentro(body); setNotice("Material publicado com sucesso."); reset(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível publicar o material."); } finally { setBusy(false); } };
  const openFile = async (item: MaterialTreinamento) => { if (!item.arquivo_url) return; try { const blob = await carregarMaterialCentro(item.id); const url = URL.createObjectURL(blob); window.open(url, "_blank", "noopener,noreferrer"); window.setTimeout(() => URL.revokeObjectURL(url), 60_000); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível abrir o arquivo."); } };
  const remove = async (item: MaterialTreinamento) => { if (!window.confirm(`Excluir o material “${item.titulo}”?`)) return; try { await excluirMaterialCentro(item.id); setItems((current) => current.filter((candidate) => candidate.id !== item.id)); setNotice("Material excluído."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível excluir o material."); } };

  return <div className="route-enter space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><IndicadorPagina>Centro de Treinamento / {heading}</IndicadorPagina><h1 className="mt-1 flex items-center gap-2 text-2xl font-extrabold tracking-[-.04em] md:text-[30px]"><Icon className="text-primary" size={25} /> {heading}</h1><p className="mt-1.5 text-xs text-muted-foreground">Materiais organizados para apoiar a operação e o desenvolvimento da equipe.</p></div>{isManager && <Button type="button" onClick={() => setFormOpen((value) => !value)} className="h-9 gap-2 text-[11px]"><Plus size={14} /> Novo material</Button>}</div>
    {(notice || error) && <div className={`rounded-lg border p-3 text-[11px] ${error ? "border-red-400/30 bg-red-400/10 text-red-200" : "border-emerald-400/30 bg-emerald-400/10 text-emerald-200"}`}>{error || notice}</div>}
    {formOpen && <form onSubmit={submit} className={`${card} grid gap-3 p-4 md:grid-cols-2`}><div className="md:col-span-2"><h2 className="text-sm font-bold">Publicar {heading.toLowerCase()}</h2><p className="mt-1 text-[10px] text-muted-foreground">Aceita vídeo MP4/WebM, PDF ou HTML. Os arquivos são armazenados no R2.</p></div><input value={title} onChange={(event) => setTitle(event.target.value)} required placeholder="Título" className="h-10 rounded-lg border border-border bg-background/50 px-3 text-xs outline-none focus:border-primary/60" /><input value={theme} onChange={(event) => setTheme(event.target.value)} placeholder="Tema (ex.: Financeiro, Operações...)" className="h-10 rounded-lg border border-border bg-background/50 px-3 text-xs outline-none focus:border-primary/60" /><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Descrição" className="min-h-20 rounded-lg border border-border bg-background/50 p-3 text-xs outline-none focus:border-primary/60 md:col-span-2" /><input value={videoUrl} onChange={(event) => setVideoUrl(event.target.value)} placeholder="URL de vídeo (opcional)" className="h-10 rounded-lg border border-border bg-background/50 px-3 text-xs outline-none focus:border-primary/60" /><label className="flex h-10 cursor-pointer items-center gap-2 rounded-lg border border-dashed border-primary/40 bg-primary/[.04] px-3 text-xs text-muted-foreground"><Upload size={14} /> {file?.name || "Anexar MP4, WebM, PDF ou HTML"}<input type="file" accept="video/mp4,video/webm,application/pdf,text/html,.html" onChange={(event) => setFile(event.target.files?.[0] || null)} className="hidden" /></label><textarea value={html} onChange={(event) => setHtml(event.target.value)} placeholder="HTML incorporado opcional (renderizado em sandbox)" className="min-h-24 rounded-lg border border-border bg-background/50 p-3 font-mono text-[10px] outline-none focus:border-primary/60 md:col-span-2" /><div className="flex justify-end gap-2 md:col-span-2"><Button type="button" variant="outline" onClick={reset} className="h-9 text-[11px]">Cancelar</Button><Button type="submit" disabled={busy} className="h-9 gap-2 text-[11px]"><Upload size={13} /> {busy ? "Publicando..." : "Publicar material"}</Button></div></form>}
    {loading ? <div className="skeleton h-60 rounded-xl" /> : Object.keys(grouped).length === 0 ? <div className={`${card} p-12 text-center text-xs text-muted-foreground`}>Nenhum material publicado nesta área.</div> : <div className="space-y-5">{Object.entries(grouped).map(([themeName, materials]) => <section key={themeName}><h2 className="mb-2 flex items-center gap-2 text-sm font-bold"><span className="h-1.5 w-1.5 rounded-full bg-primary" /> {themeName}</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{materials.map((item) => <article key={item.id} className={`${card} flex min-h-44 flex-col p-4`}><div className="flex items-start justify-between gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10 text-primary">{item.tipo_arquivo?.startsWith("video/") || item.video_url ? <Video size={16} /> : item.tipo_arquivo === "application/pdf" ? <FileText size={16} /> : <BookOpen size={16} />}</div>{isManager && <button type="button" onClick={() => void remove(item)} title="Excluir" className="rounded-md p-1.5 text-muted-foreground hover:text-red-300"><Trash2 size={14} /></button>}</div><h3 className="mt-4 text-sm font-bold">{item.titulo}</h3><p className="mt-1 line-clamp-3 text-[11px] leading-5 text-muted-foreground">{item.descricao || "Sem descrição."}</p>{item.conteudo_html && <iframe title={item.titulo} srcDoc={item.conteudo_html} sandbox="" className="mt-3 h-28 w-full rounded-lg border border-border bg-white" />}{(item.arquivo_url || item.video_url) && <Button type="button" variant="link" onClick={() => item.arquivo_url ? void openFile(item) : window.open(item.video_url || "", "_blank", "noopener,noreferrer")} className="mt-auto justify-start gap-1 px-0 pt-3 text-[11px] text-primary">Abrir material <ExternalLink size={12} /></Button>}</article>)}</div></section>)}</div>}
  </div>;
}
