import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { AlertTriangle, ArrowRight, BarChart3, BookOpen, Boxes, CalendarClock, CheckCircle2, ClipboardList, FileCheck2, FileText, Gauge, Loader2, Plane, Plus, RefreshCw, Scale, ShieldAlert, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { buscarCtmDashboard, type CtmDashboard, type CtmRegistro } from "@/lib/colaborador-api";
import { BarraProgresso, CabecalhoSecao, CartaoKpi, EstadoVazio, EtiquetaStatus, formatarMoeda } from "@/components/dashboard/PrimitivosDashboard";

const tabs = [
  ["overview", "Visão geral", Gauge], ["programa", "Programa", CalendarClock], ["oas", "Ordens de serviço", ClipboardList], ["orcamentos", "Orçamentos", FileText], ["componentes", "Componentes", Boxes], ["diretrizes", "Diretrizes", ShieldAlert], ["ras", "RAS", FileCheck2], ["peso", "Peso e balanceamento", Scale], ["rateio", "Rateio e horas", BarChart3],
] as const;

function texto(row: CtmRegistro | null | undefined, ...keys: string[]) { for (const key of keys) if (row?.[key] !== null && row?.[key] !== undefined && String(row[key]).trim()) return String(row[key]); return "—"; }
function numero(row: CtmRegistro | null | undefined, ...keys: string[]) { for (const key of keys) { const value = Number(row?.[key]); if (Number.isFinite(value)) return value; } return 0; }
function dataBr(value: unknown) { if (!value) return "—"; const raw = String(value).slice(0, 10); const date = new Date(`${raw}T00:00:00`); return Number.isNaN(date.getTime()) ? raw : date.toLocaleDateString("pt-BR"); }
function statusTone(status: string): "green" | "amber" | "red" | "blue" | "neutral" { const value = status.toLowerCase(); if (["ok", "regular", "concluido", "concluida", "aprovado", "conforme", "ativo"].includes(value)) return "green"; if (["urgente", "atencao", "atenção", "pendente", "aguardando_aprovacao", "em_andamento"].includes(value)) return "amber"; if (["vencido", "vencida", "critico", "crítico", "rejeitado", "cancelado", "cancelada"].includes(value)) return "red"; if (["aberto", "aberta", "em_analise"].includes(value)) return "blue"; return "neutral"; }
function statusLabel(value: unknown) { return String(value || "Sem status").replaceAll("_", " ").replace(/\b\w/g, (char) => char.toUpperCase()); }
function coluna(row: CtmRegistro, keys: string[], fallback = "—") { return texto(row, ...keys) || fallback; }

export default function CTM() {
  const [dados, setDados] = useState<CtmDashboard | null>(null);
  const [aeronaveId, setAeronaveId] = useState("");
  const [aba, setAba] = useState("overview");
  const [carregando, setCarregando] = useState(true);
  const [atualizando, setAtualizando] = useState(false);
  const [erro, setErro] = useState("");
  const carregar = useCallback(async (silencioso = false, id = aeronaveId) => { silencioso ? setAtualizando(true) : setCarregando(true); setErro(""); try { const response = await buscarCtmDashboard(id || undefined); setDados(response.data); if (!id && response.data.aeronave?.id) setAeronaveId(String(response.data.aeronave.id)); } catch (error) { setErro(error instanceof Error ? error.message : "Não foi possível carregar o CTM."); } finally { setCarregando(false); setAtualizando(false); } }, [aeronaveId]);
  useEffect(() => { void carregar(); }, []);
  const aeronave = dados?.aeronave;
  const resumo = dados?.resumo || {};
  const alertas = useMemo(() => [...(dados?.diretrizes || []).map((item) => ({ ...item, titulo: coluna(item, ["titulo", "descricao", "numero"], "Diretriz técnica"), detalhe: `Vencimento: ${dataBr(item.data_vencimento)}`, status: item.status || (item.data_vencimento && new Date(String(item.data_vencimento)) < new Date() ? "vencido" : "pendente") })), ...(dados?.componentes || []).map((item) => ({ ...item, titulo: coluna(item, ["nome", "part_number", "numero_serie"], "Componente"), detalhe: `Vida restante: ${numero(item, "percentual_vida_restante", "vida_restante").toFixed(0)}%`, status: item.status || "atencao" })), ...(dados?.oas || []).map((item) => ({ ...item, titulo: coluna(item, ["numero_oas", "titulo", "descricao"], "Ordem de serviço"), detalhe: `Entrada: ${dataBr(item.data_entrada)}`, status: item.status || "aberto" }))].slice(0, 8), [dados]);
  if (carregando) return <div className="flex min-h-[420px] items-center justify-center"><Loader2 className="animate-spin text-primary" size={26} /></div>;
  return <div className="route-enter space-y-5">
    <header className="flex flex-col gap-4 rounded-2xl border border-border bg-card/70 p-5 shadow-sm lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-primary"><Wrench size={14} /> Controle de troca e manutenção</div><h1 className="text-2xl font-extrabold tracking-tight">CTM <span className="text-muted-foreground">/ Centro de controle técnico</span></h1><p className="mt-1 max-w-2xl text-xs text-muted-foreground">Manutenção preventiva, ordens de serviço, componentes e conformidade em uma única operação.</p></div><div className="flex flex-wrap items-center gap-2"><select value={aeronaveId} onChange={(event) => { setAeronaveId(event.target.value); void carregar(false, event.target.value); }} className="h-10 min-w-[220px] rounded-lg border border-border bg-background px-3 text-xs font-semibold"><option value="">Todas as aeronaves</option>{(dados?.aeronaves || []).map((item) => <option key={item.id} value={item.id}>{coluna(item, ["matricula_registro", "matricula"])} · {coluna(item, ["modelo", "fabricante"])}</option>)}</select><Button variant="outline" onClick={() => void carregar(true)} disabled={atualizando} className="h-10 gap-2 text-xs"><RefreshCw size={14} className={atualizando ? "animate-spin" : ""} /> Atualizar</Button></div></header>
    {erro && <div className="flex items-center justify-between rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-xs text-red-600 dark:text-red-300"><span>{erro}</span><button type="button" className="font-bold underline" onClick={() => void carregar()}>Tentar novamente</button></div>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><CartaoKpi label="Manutenção ativa" value={String(resumo.itens_manutencao || 0)} detail="Itens do programa" icon={<CalendarClock size={16} />} /><CartaoKpi label="Próximos vencimentos" value={String(resumo.proximos_vencimentos || 0)} detail="Requerem acompanhamento" tone="amber" icon={<AlertTriangle size={16} />} /><CartaoKpi label="Diretrizes pendentes" value={String(resumo.diretrizes_pendentes || 0)} detail="ADs, SBs e conformidade" tone="red" icon={<ShieldAlert size={16} />} /><CartaoKpi label="Componentes em atenção" value={String(resumo.componentes_atencao || 0)} detail="Vida ou status crítico" tone="amber" icon={<Boxes size={16} />} /><CartaoKpi label="Ordens abertas" value={String(resumo.ordens_abertas || 0)} detail="OAS em andamento" tone="blue" icon={<ClipboardList size={16} />} /><CartaoKpi label="Orçamento em andamento" value={formatarMoeda(Number(resumo.orcamento_total || 0))} detail="Total dos orçamentos" tone="green" icon={<BarChart3 size={16} />} /></section>
    <Tabs value={aba} onValueChange={setAba} className="space-y-4"><div className="overflow-x-auto pb-1"><TabsList className="inline-flex min-w-max gap-1 bg-card/80 p-1">{tabs.map(([value, label, Icon]) => <TabsTrigger key={value} value={value} className="gap-1.5 text-[10px] data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"><Icon size={13} />{label}</TabsTrigger>)}</TabsList></div>
      <TabsContent value="overview"><div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><section className="rounded-xl border border-border bg-card/65"><CabecalhoSecao icon={<Plane size={15} />} title={aeronave ? `${coluna(aeronave, ["matricula_registro", "matricula"])} · ${coluna(aeronave, ["modelo", "fabricante"])}` : "Visão consolidada da frota"} detail={aeronave ? `Horas atuais: ${coluna(aeronave, ["horas_celula_atual", "horas_atual"], "Não informado")}` : "Selecione uma aeronave para detalhar"} /><div className="grid gap-3 p-4 sm:grid-cols-3"><ResumoCard label="Programa" value={String((dados?.programa || []).length)} detail="Itens cadastrados" /><ResumoCard label="OAS" value={String((dados?.oas || []).length)} detail="Ordens registradas" /><ResumoCard label="Diretrizes" value={String((dados?.diretrizes || []).length)} detail="Registros técnicos" /></div></section><section className="rounded-xl border border-border bg-card/65"><CabecalhoSecao icon={<ArrowRight size={15} />} title="Ações rápidas" detail="Atalhos para a rotina técnica" /><div className="grid grid-cols-2 gap-2 p-4">{[["Nova OAS", "oas", ClipboardList], ["Novo orçamento", "orcamentos", FileText], ["Registrar execução", "programa", CheckCircle2], ["Cadastrar componente", "componentes", Boxes], ["Diretriz AD/SB", "diretrizes", ShieldAlert], ["Ficha de peso", "peso", Scale]].map(([label, value, Icon]) => <button key={String(value)} type="button" onClick={() => setAba(String(value))} className="group rounded-lg border border-border bg-background/60 p-3 text-left transition hover:-translate-y-0.5 hover:border-primary/50"><span className="flex items-center justify-between text-primary"><Icon size={16} /><ArrowRight size={12} className="transition group-hover:translate-x-1" /></span><strong className="mt-3 block text-[10px]">{label}</strong><span className="mt-1 block text-[9px] text-muted-foreground">Abrir módulo</span></button>)}</div></section></div><section className="mt-5 rounded-xl border border-border bg-card/65"><CabecalhoSecao icon={<AlertTriangle size={15} />} title="Alertas prioritários" detail="Itens que exigem acompanhamento da equipe" />{alertas.length ? <div className="grid gap-2 p-4 md:grid-cols-2">{alertas.map((item, index) => <div key={`${item.id || item.titulo}-${index}`} className="flex items-center justify-between gap-3 rounded-lg border border-border bg-background/45 p-3"><div className="min-w-0"><p className="truncate text-xs font-bold">{item.titulo}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.detalhe}</p></div><EtiquetaStatus tone={statusTone(String(item.status))}>{statusLabel(item.status)}</EtiquetaStatus></div>)}</div> : <EstadoVazio label="Nenhum alerta prioritário" />}</section></TabsContent>
      <TabelaCTM value="programa" title="Programa de manutenção" detail="Itens preventivos por aeronave e intervalo de controle" rows={dados?.programa || []} columns={[["item", "Item"], ["categoria", "Categoria"], ["tipo_controle", "Controle"], ["intervalo_horas", "Horas"], ["intervalo_meses", "Meses"], ["status", "Status"]]} />
      <TabelaCTM value="oas" title="Ordens de serviço" detail="Ordens abertas, em andamento e concluídas" rows={dados?.oas || []} columns={[["numero_oas", "Número"], ["descricao", "Descrição"], ["oficina", "Oficina"], ["data_entrada", "Entrada"], ["status", "Status"]]} />
      <TabelaCTM value="orcamentos" title="Orçamentos" detail="Acompanhamento de fornecedores e aprovação" rows={dados?.orcamentos || []} columns={[["numero_orcamento", "Número"], ["descricao", "Descrição"], ["nome_fornecedor", "Fornecedor"], ["total", "Total"], ["status_aprovacao", "Aprovação"]]} moneyKeys={["total", "valor_total"]} />
      <TabelaCTM value="componentes" title="Componentes e itens controlados" detail="Rastreabilidade de peça, série, posição e vida restante" rows={dados?.componentes || []} columns={[["nome", "Componente"], ["part_number", "P/N"], ["numero_serie", "S/N"], ["posicao", "Posição"], ["percentual_vida_restante", "Vida restante"], ["status", "Status"]]} />
      <TabelaCTM value="diretrizes" title="Diretrizes e documentos técnicos" detail="ADs, SBs e vencimentos por data, horas e ciclos" rows={dados?.diretrizes || []} columns={[["numero", "Número"], ["titulo", "Título"], ["tipo", "Tipo"], ["data_vencimento", "Vencimento"], ["status", "Status"]]} />
      <TabelaCTM value="ras" title="RAS — Relatórios de acompanhamento" detail="Histórico de serviços, itens e documentos" rows={dados?.ras || []} columns={[["numero_ras", "Número"], ["descricao", "Descrição"], ["data_entrada", "Entrada"], ["status", "Status"], ["valor_total", "Total"]]} moneyKeys={["valor_total"]} />
      <TabsContent value="peso"><PainelVazio icon={<Scale size={22} />} title="Peso, balanceamento e carregamentos" detail="A ficha técnica, estações e carregamentos serão exibidos aqui para a aeronave selecionada." rows={dados?.carregamentos || []} /></TabsContent>
      <TabsContent value="rateio"><PainelVazio icon={<BarChart3 size={22} />} title="Rateio e horas voadas" detail="Custos fixos, variáveis, horas voadas e participação dos cotistas." rows={[]} /></TabsContent>
    </Tabs>
  </div>;
}
function ResumoCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-lg border border-border bg-background/40 p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-muted-foreground">{label}</p><strong className="mt-2 block text-xl">{value}</strong><span className="text-[9px] text-muted-foreground">{detail}</span></div>; }
function TabelaCTM({ value, title, detail, rows, columns, moneyKeys = [] }: { value: string; title: string; detail: string; rows: CtmRegistro[]; columns: Array<[string, string]>; moneyKeys?: string[] }) { return <TabsContent value={value}><section className="overflow-hidden rounded-xl border border-border bg-card/65"><CabecalhoSecao icon={<Wrench size={15} />} title={title} detail={detail} action={<Button className="h-8 gap-1.5 text-[10px]"><Plus size={13} /> Novo registro</Button>} />{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-border text-[9px] font-bold uppercase tracking-[.11em] text-muted-foreground">{columns.map(([, label]) => <th key={label} className="px-4 py-3">{label}</th>)}<th className="px-4 py-3 text-right">Ação</th></tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id || index)} className="border-b border-border/60 last:border-0 hover:bg-secondary/20">{columns.map(([key]) => <td key={key} className="px-4 py-3 text-[10px]">{moneyKeys.includes(key) ? formatarMoeda(numero(row, key)) : key.includes("data") ? dataBr(row[key]) : key === "status" || key.includes("aprovacao") ? <EtiquetaStatus tone={statusTone(String(row[key] || ""))}>{statusLabel(row[key])}</EtiquetaStatus> : <span className={key === "item" || key === "descricao" || key === "titulo" ? "font-semibold" : "text-muted-foreground"}>{texto(row, key)}</span>}</td>)}<td className="px-4 py-3 text-right"><button type="button" className="text-[10px] font-bold text-primary hover:underline">Detalhar</button></td></tr>)}</tbody></table></div> : <EstadoVazio label="Nenhum registro encontrado para esta aeronave" />}</section></TabsContent>; }
function PainelVazio({ icon, title, detail, rows }: { icon: ReactNode; title: string; detail: string; rows: CtmRegistro[] }) { return <section className="rounded-xl border border-border bg-card/65"><CabecalhoSecao icon={icon} title={title} detail={detail} />{rows.length ? <div className="p-4"><BarraProgresso value={62} color="blue" /></div> : <EstadoVazio label="Módulo pronto para receber os registros" />}</section>; }
