import { ArrowRight, CheckCircle2, SlidersHorizontal } from "lucide-react";
import { EstadoVazio, IndicadorPagina } from "@/components/dashboard/PrimitivosDashboard";
import { nomesAmbiente, type Ambiente, type ItemMenu } from "@/types/navegacao";

export default function ModuloInterno({ ambiente, menu, aoVoltar }: { ambiente: Ambiente; menu: ItemMenu; aoVoltar: () => void }) {
  const Icon = menu.icon;
  return <div className="route-enter"><div className="mb-6 flex items-end justify-between gap-4"><div><IndicadorPagina>{nomesAmbiente[ambiente]} / módulo</IndicadorPagina><h1 className="text-2xl font-extrabold tracking-[-.04em] md:text-[30px]">{menu.label}</h1><p className="mt-1.5 max-w-2xl text-xs leading-relaxed text-muted-foreground">Área preparada para receber a operação de {menu.label.toLowerCase()} com dados reais do Share Brasil.</p></div><button type="button" onClick={aoVoltar} className="flex items-center gap-2 rounded-lg border border-border bg-card px-3.5 py-2.5 text-[10px] font-bold text-muted-foreground hover:bg-secondary hover:text-foreground"><ArrowRight size={13} className="rotate-180" /> Voltar à visão geral</button></div><div className="grid gap-4 sm:grid-cols-3"><section className="rounded-xl border border-border bg-card/70 p-5 sm:col-span-2"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon size={21} /></div><h2 className="mt-5 text-sm font-bold">Estrutura pronta para {menu.label}</h2><p className="mt-2 max-w-lg text-xs leading-relaxed text-muted-foreground">A navegação, o contexto do departamento e a identidade visual já estão separados. Os formulários, filtros, permissões e integrações serão adicionados sem misturar o módulo com os demais ambientes.</p><div className="mt-6 grid gap-2 sm:grid-cols-3"><MiniCampo label="Área" valor={nomesAmbiente[ambiente]} /><MiniCampo label="Acesso" valor="Interno" /><MiniCampo label="Status" valor="Em preparação" /></div></section><section className="rounded-xl border border-border bg-card/70 p-5"><div className="flex items-center gap-2 text-[#f4cc64]"><SlidersHorizontal size={16} /><span className="text-[10px] font-bold uppercase tracking-[.12em]">Próximos passos</span></div><div className="mt-5 space-y-4"><Checklist texto="Layout e navegação" concluido /><Checklist texto="Permissões por área" /><Checklist texto="Dados do módulo" /><Checklist texto="Ações e relatórios" /></div></section></div><section className="mt-5 rounded-xl border border-border bg-card/70"><EstadoVazio label="Nenhum registro carregado nesta etapa" /></section></div>;
}
function MiniCampo({ label, valor }: { label: string; valor: string }) { return <div className="rounded-lg border border-border/70 bg-secondary/25 p-2.5"><p className="truncate text-[9px] text-muted-foreground">{label}</p><p className="mt-2 text-[11px] font-bold">{valor}</p></div>; }
function Checklist({ texto, concluido = false }: { texto: string; concluido?: boolean }) { return <div className="flex items-center gap-2.5 text-[11px]">{concluido ? <CheckCircle2 size={15} className="text-[#6bd188]" /> : <span className="h-[15px] w-[15px] rounded-full border border-border" />}<span className={concluido ? "text-foreground" : "text-muted-foreground"}>{texto}</span></div>; }
