import { useState } from "react";
import { BookOpen, ChevronDown, ExternalLink, Info } from "lucide-react";

const seriesNacionais = [
  ["B", "CRN de Recife"], ["D", "CRN de São Paulo"], ["E", "CRN de Curitiba"],
  ["F", "CRN de Brasília"], ["G", "CRN de Manaus"], ["Z", "Centro Geral de NOTAM"],
];
const seriesInternacionais = [
  ["I", "FIR Recife"], ["J", "FIR Brasília"], ["K", "FIR Curitiba"], ["N", "FIR Atlântico"], ["O", "FIR Amazônica"],
];
const firs = [["SBBS", "FIR Brasília"], ["SBCW", "FIR Curitiba"], ["SBAZ", "FIR Amazônica"], ["SBRE", "FIR Recife"], ["SBAO", "FIR Atlântico"]];

export default function NotamLeituraAjuda() {
  const [aberto, setAberto] = useState(false);
  return <section className="rounded-xl border border-primary/25 bg-primary/[.04]">
    <button type="button" onClick={() => setAberto((current) => !current)} className="flex w-full items-center justify-between gap-3 p-4 text-left"><span className="flex items-center gap-2"><BookOpen size={16} className="text-primary" /><span><span className="block text-xs font-bold">Como ler um NOTAM</span><span className="mt-0.5 block text-[10px] text-muted-foreground">Guia rápido de identificação, série, FIR e qualificadores Q)</span></span></span><ChevronDown size={16} className={`text-primary transition-transform ${aberto ? "rotate-180" : ""}`} /></button>
    {aberto && <div className="space-y-5 border-t border-primary/15 p-4 text-[10px] leading-relaxed md:p-5">
      <div className="flex items-start gap-2 rounded-lg border border-sky-400/20 bg-sky-400/[.06] p-3 text-muted-foreground"><Info size={15} className="mt-0.5 shrink-0 text-sky-300" /><p><strong className="text-foreground">Atenção operacional:</strong> esta ajuda explica a estrutura do texto. A decisão de utilização do aeródromo, rota ou espaço aéreo deve sempre considerar o NOTAM oficial vigente e os procedimentos do despacho.</p></div>
      <div><h3 className="text-xs font-bold text-primary">1. Linha de identificação</h3><p className="mt-1 text-muted-foreground">O cabeçalho normalmente aparece como <code className="rounded bg-secondary px-1.5 py-0.5 font-mono text-foreground">[Série][Número]/[Ano] [Tipo]</code>. A letra identifica a série, o número é sequencial dentro da série e o ano usa os dois últimos dígitos.</p><div className="mt-2 grid gap-2 sm:grid-cols-3"><div className="rounded-lg border border-border bg-secondary/25 p-3"><p className="font-bold text-foreground">Série</p><p className="mt-1 text-muted-foreground">Indica o centro expedidor ou a FIR de abrangência.</p></div><div className="rounded-lg border border-border bg-secondary/25 p-3"><p className="font-bold text-foreground">Número / ano</p><p className="mt-1 text-muted-foreground">Sequencial independente por série, reiniciado a cada ano.</p></div><div className="rounded-lg border border-border bg-secondary/25 p-3"><p className="font-bold text-foreground">Tipo</p><p className="mt-1 text-muted-foreground"><strong>N</strong> = novo; <strong>R</strong> = substitui; <strong>C</strong> = cancela.</p></div></div></div>
      <div className="grid gap-4 lg:grid-cols-2"><div><h3 className="text-xs font-bold text-primary">Séries nacionais</h3><div className="mt-2 grid grid-cols-2 gap-2">{seriesNacionais.map(([serie, descricao]) => <div key={serie} className="rounded-md border border-border bg-secondary/25 p-2"><strong className="font-mono text-foreground">{serie}</strong><span className="ml-2 text-muted-foreground">{descricao}</span></div>)}</div></div><div><h3 className="text-xs font-bold text-primary">Séries internacionais</h3><div className="mt-2 grid grid-cols-2 gap-2">{seriesInternacionais.map(([serie, descricao]) => <div key={serie} className="rounded-md border border-border bg-secondary/25 p-2"><strong className="font-mono text-foreground">{serie}</strong><span className="ml-2 text-muted-foreground">{descricao}</span></div>)}</div></div></div>
      <div><h3 className="text-xs font-bold text-primary">2. Linha Q) — qualificadores</h3><p className="mt-1 text-muted-foreground">A segunda linha começa com <code className="rounded bg-secondary px-1.5 py-0.5 font-mono text-foreground">Q)</code> e reúne códigos ICAO que resumem o evento. Leia os campos nesta ordem:</p><div className="mt-2 overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="border-b border-border text-[9px] uppercase tracking-[.1em] text-muted-foreground"><th className="px-2 py-2">Campo</th><th className="px-2 py-2">O que informa</th><th className="px-2 py-2">Como interpretar</th></tr></thead><tbody>{[["FIR", "Código ICAO da FIR responsável", "Área de controle que publicou ou coordena o NOTAM."], ["Assunto", "Tipo de restrição ou ocorrência", "Pista fechada, obstáculo, auxílio à navegação, espaço aéreo etc."], ["Tráfego afetado", "IFR, VFR ou ambos", "Identifica quais regras de voo são impactadas."], ["Propósito", "Operação afetada", "Informação, atenção, operação imediata ou planejamento."], ["Âmbito", "Área ou serviço afetado", "Aeródromo, navegação, serviços ou espaço aéreo."], ["Altitude", "Limite inferior e superior", "Faixa vertical afetada pela restrição."], ["Localização", "Coordenada do evento", "Ponto geográfico associado ao NOTAM."], ["Raio", "Distância de influência", "Extensão em milhas náuticas a partir da localização."]].map(([campo, oque, interpretar]) => <tr key={campo} className="border-b border-border/50"><td className="px-2 py-2 font-bold text-foreground">{campo}</td><td className="px-2 py-2 text-muted-foreground">{oque}</td><td className="px-2 py-2 text-muted-foreground">{interpretar}</td></tr>)}</tbody></table></div></div>
      <div><h3 className="text-xs font-bold text-primary">FIRs brasileiras mais comuns</h3><div className="mt-2 flex flex-wrap gap-2">{firs.map(([codigo, nome]) => <span key={codigo} className="rounded-md border border-border bg-secondary/25 px-2.5 py-1.5"><strong className="font-mono text-foreground">{codigo}</strong><span className="ml-1.5 text-muted-foreground">{nome}</span></span>)}</div></div>
      <a href="https://aisweb.decea.mil.br/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-bold text-primary hover:underline">Consultar AISWEB / DECEA <ExternalLink size={11} /></a>
    </div>}
  </section>;
}
